Repository kyverno/policies, pull requests merged in 2021-07, with the labels that each got.

#74 Policy updates
  cert-manager/limit-dnsnames.yaml
  cert-manager/restrict-issuer.yaml
  other/add-pod-proxies.yaml
  other/block_updates_deletes.yaml
  other/ensure_probes_different.yaml
  other/memory-requests-equal-limits.yaml
  other/unique-ingress-paths.yaml
Labels: sample

#76 fix deny logic
  other/ensure_probes_different.yaml
Labels: bug

#83 Added result in the test.yaml file for rule validate-crio-sock-mount
  best-practices/disallow_cri_sock_mount/test.yaml
Labels: documentation, sample
